[project]
name = "solver-multiRPC"
version = "3.0.0"
dependencies = [
    "web3>=6.0.0",
    "multicallable>=6.0.0",
    "eth-account>=0.12.2",
    "logmon @ git+https://zxcode.xyz/pub/logmon.git@73c1bfe9",
]
[tool.setuptools]
package-dir = {"" = "src"}